version: "3.9"
services:
  master:
    build: ./master_sim/
    volumes:
        - "./master_sim/:/opt/"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports: 
      - "8189:8189"


